import { Navigation } from '@/components/navigation';

export default function TermsPage() {
  return (
    <>
      <Navigation />
      <main className="min-h-screen bg-gray-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
          <div className="bg-white rounded-lg shadow-sm p-8">
            <div className="text-center mb-8">
              <h1 className="text-3xl font-bold text-gray-900 mb-4">
                Terms and Conditions
              </h1>
              <p className="text-lg text-gray-600">
                Agreeable.ca Service Agreement
              </p>
              <p className="text-sm text-gray-500 mt-2">
                Last updated: {new Date().toLocaleDateString()}
              </p>
            </div>

            <div className="prose max-w-none">
              <h2 className="text-xl font-semibold text-gray-900 mb-4">1. Acceptance of Terms</h2>
              <p className="text-gray-600 mb-6">
                By accessing and using the Agreeable.ca service, you accept and agree to be bound by the terms 
                and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
              </p>

              <h2 className="text-xl font-semibold text-gray-900 mb-4">2. Service Description</h2>
              <p className="text-gray-600 mb-4">
                Agreeable.ca provides an online platform for creating cohabitation agreements and family contracts. 
                Our service includes:
              </p>
              <ul className="list-disc list-inside text-gray-600 mb-6 space-y-1">
                <li>Document template creation and customization</li>
                <li>Form-based data collection for personalized agreements</li>
                <li>PDF generation of completed contracts</li>
                <li>Secure storage of contract information</li>
                <li>Administrative tools for contract management</li>
              </ul>

              <h2 className="text-xl font-semibold text-gray-900 mb-4">3. Legal Disclaimer</h2>
              <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-6">
                <p className="text-yellow-800 font-medium mb-2">IMPORTANT LEGAL NOTICE:</p>
                <p className="text-yellow-700 text-sm">
                  This service provides document templates and form completion tools only. We do not provide legal advice, 
                  legal representation, or legal services of any kind. The documents generated by this service are templates 
                  that may require modification to suit your specific circumstances.
                </p>
              </div>
              <p className="text-gray-600 mb-6">
                <strong>Independent Legal Advice Required:</strong> We strongly recommend that both parties seek independent 
                legal advice from qualified Alberta family law lawyers before signing any cohabitation agreement or family contract. 
                A lawyer can ensure the agreement meets your specific needs and complies with current Alberta law.
              </p>

              <h2 className="text-xl font-semibold text-gray-900 mb-4">4. User Responsibilities</h2>
              <p className="text-gray-600 mb-4">As a user of this service, you agree to:</p>
              <ul className="list-disc list-inside text-gray-600 mb-6 space-y-1">
                <li>Provide accurate and complete information</li>
                <li>Use the service only for lawful purposes</li>
                <li>Maintain the confidentiality of your account credentials</li>
                <li>Review all generated documents carefully</li>
                <li>Seek appropriate legal advice before executing any agreement</li>
                <li>Not use the service to create documents for illegal purposes</li>
              </ul>

              <h2 className="text-xl font-semibold text-gray-900 mb-4">5. Privacy and Data Protection</h2>
              <p className="text-gray-600 mb-4">
                We take your privacy seriously and are committed to protecting your personal information:
              </p>
              <ul className="list-disc list-inside text-gray-600 mb-6 space-y-1">
                <li>Personal information is collected only as necessary to provide our services</li>
                <li>Data is stored securely using industry-standard encryption</li>
                <li>Information is not shared with third parties except as required by law</li>
                <li>Users may request deletion of their data at any time</li>
                <li>We comply with applicable Canadian privacy laws</li>
              </ul>

              <h2 className="text-xl font-semibold text-gray-900 mb-4">6. Payment and Refunds</h2>
              <p className="text-gray-600 mb-4">
                Payment terms for our services:
              </p>
              <ul className="list-disc list-inside text-gray-600 mb-6 space-y-1">
                <li>All fees are in Canadian dollars and include applicable taxes</li>
                <li>Payment is required before document generation and download</li>
                <li>Refunds may be provided at our discretion within 30 days of purchase</li>
                <li>No refund will be provided if documents have been downloaded or used</li>
                <li>Technical issues will be resolved or refunded as appropriate</li>
              </ul>

              <h2 className="text-xl font-semibold text-gray-900 mb-4">7. Limitation of Liability</h2>
              <p className="text-gray-600 mb-6">
                To the maximum extent permitted by law, Agreeable.ca and its operators shall not be liable for any 
                direct, indirect, incidental, special, consequential, or punitive damages arising from your use of this service, 
                including but not limited to damages for loss of profits, goodwill, use, data, or other intangible losses, 
                even if we have been advised of the possibility of such damages.
              </p>

              <h2 className="text-xl font-semibold text-gray-900 mb-4">8. No Warranty</h2>
              <p className="text-gray-600 mb-6">
                This service is provided "as is" without warranty of any kind. We make no representations or warranties 
                regarding the accuracy, completeness, or suitability of the documents generated. The templates provided 
                may not be suitable for all situations and may require modification by qualified legal professionals.
              </p>

              <h2 className="text-xl font-semibold text-gray-900 mb-4">9. Intellectual Property</h2>
              <p className="text-gray-600 mb-6">
                All content, templates, software, and materials provided through this service are owned by or licensed to 
                Agreeable.ca. Users receive a limited license to use the service and download generated documents 
                for their personal use only. Commercial use or redistribution is prohibited without explicit written permission.
              </p>

              <h2 className="text-xl font-semibold text-gray-900 mb-4">10. Termination</h2>
              <p className="text-gray-600 mb-6">
                We reserve the right to terminate or suspend access to our service immediately, without prior notice or liability, 
                for any reason whatsoever, including without limitation if you breach the Terms of Service.
              </p>

              <h2 className="text-xl font-semibold text-gray-900 mb-4">11. Governing Law</h2>
              <p className="text-gray-600 mb-6">
                These Terms shall be interpreted and governed by the laws of the Province of Alberta and the laws of Canada 
                applicable therein. Any disputes arising under these terms shall be subject to the exclusive jurisdiction 
                of the courts of Alberta.
              </p>

              <h2 className="text-xl font-semibold text-gray-900 mb-4">12. Changes to Terms</h2>
              <p className="text-gray-600 mb-6">
                We reserve the right to modify these terms at any time. Changes will be effective immediately upon posting 
                to this page. Continued use of the service after changes constitutes acceptance of the modified terms.
              </p>

              <h2 className="text-xl font-semibold text-gray-900 mb-4">13. Contact Information</h2>
              <p className="text-gray-600 mb-6">
                If you have any questions about these Terms and Conditions, please contact us through our contact page 
                or support channels provided on the website.
              </p>

              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mt-8">
                <p className="text-blue-800 text-sm">
                  <strong>Remember:</strong> By using our service and generating documents, you acknowledge that you have read, 
                  understood, and agree to be bound by these Terms and Conditions. You also acknowledge that you understand 
                  the importance of obtaining independent legal advice before executing any legal document.
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}