name: Schema Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate-schema:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
      
    - name: Wait for deployment
      run: sleep 30
      
    - name: Validate production schema
      run: npm run schema:validate
      continue-on-error: false
      
    - name: Comment on PR (if schema issues)
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ **Schema Validation Failed**\n\nDatabase schema is out of sync. Please run `npm run schema:validate` locally to see details and fix before merging.'
          })